name: Hello World

# Events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Workflow / Jobs
jobs:
  hello-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello 1
        run: echo "Hello World 1"
        shell: bash
  hello-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello 2
        run: echo "Hello World 2"
        shell: bash
